language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
addons:
  ssh_known_hosts: ec2-18-156-118-22.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=eurelozi-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-18-156-118-22.eu-central-1.compute.amazonaws.com
    'bash launch_build.sh'
  on:
    branch: master
env:
  global:
    - secure: KADw5mg6GdrNNPQMdGFRtSp0i8hhAOqlUKVxoatyOvHmVvaC6+x+eVggIb5xgrTJ7JiERV9AEiO/JaZ8TLGH1SLporlV5Bkf8RoNmVvucSXahr122jvbFrBJhvB/5+FOWav1QdIh/M5Dib2EGLnpu+PnWDQgNYHmUrq8/ZdX5O3pEH8t0UmWHOgrgTAwMPNlayuNJaQQhiHTNc2dVCBWJiICWKtWz34gbQExm9rWmaBbx471CQPTaCy954wbByMJWaZxe5ybsxX25RFm6R3Mx6TjlbeWhwYQL6tS0w6T6FK2xQJyb/GsKKD8lMAPC5S/7B2feDVR7RrwvHZS8mbGYYMq8kfJAct4yfdz6X79+piZqBkPiWyDGhtfUIqrCxvRg9OquMAtdQSBAW5Kz4Y6D/xOH+amXBfiFvxAJNEr4e+OOSJkYeXtQKUKZdw/8UEYKj2H5L8X+YL3SMxmuYGR2mSmKcSC/YbYvkHt30Y1gWELqufCSt3W0zM0Rqr1PDO9kO6UQYCv/hGYUkwPo/EDAbSHcfddobZENVMdwUQJogThRUdgVnhU7DcoBp70QrUli7lC4Mb5sdGqRVQcCHzNE/4VdSC/pGRLikS3bLu5e9rihdGOXuhHlFFJRkcJk58l/3Fs58SMGZpyOyX/Ho9RlST4qYMfQZtvDGXwBrqvZcs=
    - secure: K0iT2x04ycy25QxOhf9z4gav+4x8gvM2Z/1NWEfZ7Nyvtc1AirRHEdKC3afAwLTxSiXb9L/f/EYVLDP30pgF+TWn/j2Q63PNfnDLoKnjLRp/TVg1K4q7riIt1gzehvOdr9rJyVDykztlQbMKacB5LJ91ctyWkvAuGuEvIY6Hg+A7HEE0rHBa+mOMchbMddRMRWjjhJsAcyP+jwSAEmDQNZml2DYG1mi7jF9IaSo9nz64gqrWX1GC5lGqEDtCYFOBUFLhWfKcT90Uogn4g8dkCOtOwEXvBNUVFwHQSczh+67n4DgYFF+sfDYKjt5wpww4xfQF8oZSnDFja4vCJOyuqr3LIqp6SVTqTLTRONBGWSIo9V6MzMaswGSZdWNA6uT973bTuMGPIiSCj/0+RLJ97jXaCNaKJ118iF9np/LMMYY8jxOrnB95HzFzRHyuCWl25opfwOTW5nN2vvmgL+4WmoMZ4oZU+PfUY4IDeZXl0QPdfIUkEs8/o//wsYCQ89Alaja6fTiOxX5+w6mMWDZWgDtHC/j5oMBgrsJpDH2exMh1FzzIsY8DfvJ8cKeNSz227uEzCV/QhuQP+rWw+D6pp56+DgIsJZE/uhgSMJXKMR9+UgK6el+b2jYYu0BdD8dKR3d69yQFFnHPMGjb0K/KyJ4zdDbSe4QuOQx8yYwTr+k=
    - secure: HafZJHEDUpi59hW1dP4cO0Rt1V4WbodTwMWUsp6rdpvwbDZ76zpIf/LwL0WFtXKSCMcaWEus3X4+PJCfThQ29XNwUZij+NNKhF+SyT8974HuyysBfw3dBj5D6W2mcBa8HXH9xUnm0C2BACF5Gf65OSzj/9Wneqatxki7xN8mQ2/AdCJYiczZvHH5NwfzbGqHEJCMT2dSokVnTHXCOjqjrge1GAstUC+HWHg+zNjGY73B6RppMVS5l9yae2OqBlVk6mug85jqHIKYkFwmXJBXAUsxfEZ8QVKSx52gIsDmdpYeoEeckB55N0oGAyYhgmXSBdSVkSkCdyPx+2dkNV38OxwU+ljy6vz0JPM9FSaT0kofMCjJpr6vlTRnc5aYTvuO4vgZbdd1hzAlfi08y3AYvnfDVGEBX75hvMSDQGFXIfz148B0EI1IB6F+cx3l/cGm7+kehCfMbf69ZWOJS28IVpB2FjZN+Eaj5KHC7+MUSxerreF/alqYTl1jDUYUqaNUxS1lJKH7QmlDLiqdAWQTdCaYlbuKPtXguqUFQm9efVsIdZNY/H3oJn66ITWwdMpwyn3h6eHG7piSAuoG4WsUfDAespGEQ8838TBHKQjicZGCHUpR5Bmk+GYw2QMOh/bq73cRFpVg6Zy8Lk1WoaYXoafY3A8t57H+ymHsoLKDGQo=
    - secure: aX6/vKos1zpR5eWwq1JdEFANzU+JEZYiinXCd/iOmWEH7UKvnL0BtsLrvqZMVjcjlDMTjqlijE8Jbr/0zlhslZJd25MF+gq7oqqRVVOz/1OoTENwWR8mLYo+DboVNvLecA5ZtIMV3QyuT+ePRLTBvcyXJCCULMlSxoB8wPm6ox8/OcdDLlDd07xzActqB4DKohUcx/HMtTm3yptormHqXl+3CccsqD5wlFzlHcN8wZRGMdMJOU2O+AYF19XdR1U5NJMHcZj9/GZHSJ/V4KPt7269rQTV8UNrDJ6JH7vY3zfQU18IK9VyKRHBIBCCe3gm3mvdoV2Rk5jdeLOlEMZY2yELLGQitIbn9yXTgcRN3xdGZ3rbAxhRGEeoOujQ6xhLimn/4kp/JBGJg3AxsFGVnvQakdTk3/w06V8oforEbxkYK/4boAYZMrCsYHnyIV/vvOuQqm1zaoXJo9LIIyUNGqGMj6RdRAYs2VQ8AUeIPYK0ISw3PUVJxf7nKe3O+mkdI1Qglpr0SeKHcOVfXmaD5QpVvbojbv+3dsgwpXduAnBd9wGjXb7ZwKr0NQV+k9PeNHuJ2CdhrP6HZ1Ljv+YSJ1LDZp9OW+xfBL4l7tVE/iWUfvKRl5kl4a1OzQis9oKlhZpAv7p+bIT9mX4Otw5ZzaIFh6ZyMXdDGUOeiJUnOcI=
    - secure: K+xUYt/Zq83O8cOBHST53b2yhKph24S8TC1HigsAxbQQeWdDeI9MTkA+6Xlx5HdeI/Mp9GcFhhLkGKydwpnGsSYCudZi4igJjmshN93PEXUq8Z+QpxW5cODhw5quNMXxWvBzLCMrpT7jsxPWP//xXl0MCM0aFELhgO4/SuQmJa39dV70mSNhUivpgSpeIYK2MirG3RBYqUJS0SC2bSRzvsUPDO4cuofZ6akZrkfMaiIvjxLPdHdvOWATFds1jni9qOTLofYqxpqGYMdo9vJCTvFZKeBxIJxPH8Ie2GrMds0D63m/pRK7oSAp8Eri/UgMfbBfcsQslE5/x/T0agRyVx3LSggQAeB8NFSgHDCad0Iug7KiboxrDZQJBpDj7WuFO4oC/X/bLxs2sIIzo29T/mUGvhKMd1G5S3hct9TqUt7vae9junIE8TDBTHIDouKPJI3XC410xao0njqkNVqU4VZ8VYhBzRhNWuPbCtiM+DaD/lFeUv072cZWTB9b0FwmN2aWd63DHjXgAtAr8qQqQ11g0KCqIVqL8vgChyQ0xq+Q6Ed/VCa/PTw5/ZQ8T53WUk62bRy/q6L5//H3lJKdNzq0WHLXYsvpqmXGCT4bYexuOvvabnkB58vvYI242qmaiVTHsP+DgtmHnZ5JrEizR2ak8BbkpJNewhDLNEgx7q0=
